#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          myservice
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DAEMON=rtl_tcp
DAEMON_DIR=/usr/bin
DAEMON_NAME=rtl-tcp

DEVICE="-d 0"         #number of drvice
LISTIP="-a 0.0.0.0"   #listen ip address
PORT="-p 1482"        #listen port (defaulr: 1234)
PPM="-P 58"           #ppm_errors (defaulr: 0)
#SMPR="-s 16384000"   #samplerate

# Add any command line options for your daemon here
DAEMON_OPTS="$DEVICE $LISTIP $PORT $PPM $SMPR"

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start() {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    if [ -x $DAEMON ]; then
        log_action_msg "$DAEMON_NAME binary missing - not starting"
        log_end_msg 1
    fi

    if start-stop-daemon --start --background --chuid $DAEMON_USER --chdir $DAEMON_DIR --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS; then
        log_end_msg 0
    fi
}
do_stop() {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
